[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet] # Match the cluster where you're deploying
solciv = "Fhs1N6Mp1DcKEQXuoPkWfBz636Mq5BBRPY9epNNWKi7j"
mpl_token_metadata = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[provider]
cluster = "Devnet" # Ensure this matches the target cluster
wallet = "/home/infcapital/work/projects/1_solana/0_foundation/config/mintAuthority.json"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
